@host=http://localhost:5071
@adminId=2150e333-8fdc-42a3-9474-1a3956d46de8

POST {{host}}/Subscriptions
Content-Type: application/json

{
    "SubscriptionType": "Free",
    "AdminId": "{{adminId}}"
}

# {
#     "Id": "{{adminId}}"
#     "SubscriptionType": "Free", // "Starter", "Pro"
# }