@host=http://localhost:5209
@adminId=78da91d2-891f-4eb4-ae29-5820b76c5203

POST {{host}}/Subscriptions
Content-Type: application/json

{
    "SubscriptionType": "Starter",
    "AdminId": "{{adminId}}"
}

# {
#     "Id": "{{adminId}}"
#     "SubscriptionType": "Free", // "Starter", "Pro"
# }